fix(sensors): remove dash from sensor names
JurajNyiri/HomeAssistant-Tapo-Control pull request #208
Opened 2022-10-17 12:41 UTC by CFenner

The integration provides sensors names which are prefixed with the camera name separated with a dash (`-`): `Flur -HD`, `Flur - Motion`

Within HA the camera name is trimmed again from the sensor name and it looks a bit odd like this:

<img width="896" alt="Bildschirmfoto 2022-10-17 um 14 34 05" src="https://user-images.githubusercontent.com/9592452/196179046-938d79cc-e20a-404c-b04c-bf95bccb2522.png">

Therefore I suggest to simply remove the `-`.

2022-10-17 12:56 UTC, JurajNyiri commented
Thank you for the PR, could you please also modify this for camera entities?

2022-10-17 13:17 UTC, JurajNyiri commented
Thank you!

2022-10-17 13:18 UTC, JurajNyiri requested changes

2022-10-17 13:18 UTC, JurajNyiri commented on custom_components/tapo_control/camera.py
> +        return self.getName().replace(' - ', ' ')
Instead of replacing it here, I recommend replacing it inside

```
 def getName(self):
        name = self._attributes["device_alias"]
        if self._hdstream:
            name += " - HD"
        else:
            name += " - SD"
        return name
```
So it would become

```
 def getName(self):
        name = self._attributes["device_alias"]
        if self._hdstream:
            name += " HD"
        else:
            name += " SD"
        return name
```

2022-10-17 13:29 UTC, CFenner commented on custom_components/tapo_control/camera.py
> +        return self.getName().replace(' - ', ' ')
Sure! Missed that code part..

2022-10-17 16:18 UTC, JurajNyiri approved these changes

2022-10-17 16:18 UTC, merged

2022-10-18 13:34 UTC, JurajNyiri commented
Released in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/4.0.0 .