fix(entities): correct unavailable state
JurajNyiri/HomeAssistant-Tapo-Control pull request #229
Opened 2022-10-21 11:44 UTC by CFenner

When the camera is not available these calls fail with an exception causing the entities not go into `unavailable` state.

<img width="934" alt="Bildschirmfoto 2022-10-21 um 13 28 56" src="https://user-images.githubusercontent.com/9592452/197188085-a8d1f0b9-ef42-4abe-a287-fb0298da5646.png">

Adding `try/catch` in `select` and `camera` seems to fix this for most of the cases, `button` and `number` are still marked as `available`.

2022-10-21 12:01 UTC, CFenner commented on custom_components/tapo_control/select.py
> +            self._attr_current_option = None
```suggestion
```

2022-10-21 12:28 UTC, JurajNyiri reviewed
We can remove all async_update functions in entities they are no longer needed

2022-10-21 17:00 UTC, JurajNyiri requested changes
See comment above

2022-11-17 08:29 UTC, JurajNyiri commented
Thank you!!

2022-11-17 08:29 UTC, merged

2022-11-17 08:50 UTC, CFenner commented
I haven't handed your comment yet, just solved the merge conflict. Was about to do that.

2022-11-17 12:13 UTC, JurajNyiri commented
My bad, thank you!