Person detection
JurajNyiri/HomeAssistant-Tapo-Control pull request #269
Opened 2023-01-05 14:40 UTC by fredrikhaggbom

2023-01-06 11:25 UTC, JurajNyiri requested changes
Thank you for your contribution! We do not need to modify camera.py at all for this PR. The rest looks good, I still have to take a look into pytapo changes and test this.

2023-01-06 11:25 UTC, JurajNyiri commented on custom_components/tapo_control/camera.py
> +            )
We should not make additional calls here, it should be already available inside camData object supplied with every update. If the function getPersonDetection is not included in the `.getMost` call in pytapo, it needs to be added there and then into utils so that the camData has the data of that function.

2023-01-06 11:25 UTC, JurajNyiri commented on custom_components/tapo_control/camera.py
> +            )
Also no need to do it in brand property.

2023-01-06 11:25 UTC, JurajNyiri commented on custom_components/tapo_control/camera.py
> +
We have select, no need to add camera functions.

2023-01-06 11:25 UTC, JurajNyiri commented on custom_components/tapo_control/camera.py
> +
We have select, no need to add camera attribute.

2023-01-06 19:13 UTC, JurajNyiri commented
Dev branch of pytapo has been released as 2.9 version having all these functions.

2023-01-09 10:59 UTC, fredrikhaggbom commented on custom_components/tapo_control/camera.py
> +            )
Camera.py has been reset, and no changes are no longer made to the file in this PR

2023-01-09 11:50 UTC, JurajNyiri approved these changes

2023-01-09 13:47 UTC, JurajNyiri requested changes
Great work, can we also add `getPersonDetection` into `pytapoFunctionMap` so that the call does not need to be made inside `isCacheSupported` and `check_and_create` reducing the amount of network calls?

2023-01-09 14:08 UTC, merged