Fix for #315
JurajNyiri/HomeAssistant-Tapo-Control pull request #316
Opened 2023-04-20 21:12 UTC by nopper

2023-04-20 21:33 UTC, JurajNyiri commented
Thank you! I will test and release tomorrow, code changes look great!

2023-04-21 17:59 UTC, JurajNyiri requested changes

2023-04-21 17:59 UTC, JurajNyiri commented on custom_components/tapo_control/utils.py
> +        coldFilePath.replace("/storage/", "/www/").replace(".mp4", "")
This needs to be

```
coldFilePath.replace("/.storage/", "/www/").replace(".mp4", "")
```

Otherwise I got error 

```
2023-04-21 17:57:48.727 ERROR (MainThread) [custom_components.tapo_control] substring not found
```
As the hotFilePath is not properly generated.

2023-04-21 18:22 UTC, nopper commented
Addressed your comment. I think you can integrate it now.

2023-04-21 18:55 UTC, JurajNyiri commented
Works great, thank you!

2023-04-21 18:55 UTC, merged