Feature/ Hub Siren and C420 cameras fixes
JurajNyiri/HomeAssistant-Tapo-Control pull request #559
Opened 2024-04-19 00:28 UTC by marcosngomezi

2024-04-19 16:39 UTC, JurajNyiri commented
Hi @marcosngomezi could you please test this branch https://github.com/JurajNyiri/pytapo/tree/experiment-multiple-params-getSirenTypeList

<img width="655" alt="Screenshot 2024-04-19 at 18 35 34" src="https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/5785999/077b4741-7b4e-410d-ab5e-bf9b6e43f0d5">

My cameras do not support this function at all so I cannot test.

<img width="655" alt="Screenshot 2024-04-19 at 18 35 34" src="https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/5785999/bb4348a7-14de-4369-95e9-e3e719d64140">

What is the response you get when you run `print(tapo.getMost()["getSirenTypeList"])`? and what is the response when you run `getHubSirenTypeList(self)` and `getAlarmConfig(self)`?

2024-04-20 13:38 UTC, marcosngomezi commented
Can't do the test right now, but already tested to send both msg_alarm and siren on a command and ignores the second one or fails depending on the method, I will test it with your branch and report back

2024-04-22 21:40 UTC, marcosngomezi commented
I'm back @JurajNyiri 
Sent to both devices hub and camera each command:
![image](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/92400610/c6074411-2170-40c9-8560-042149966ed2)
And the response for each was:
![image](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/92400610/e0e6d281-85b9-48da-bdef-9468501ae11f)

As commented on the first image getHubSirenTypeList on the camera throws an exception not sure why that error generates an exception while other don't

2024-04-22 21:54 UTC, marcosngomezi commented
This PR is not solving #556, gives the same functionality but only for hub siren, not camera, I can look at it and try to solve it in another PR

2024-04-22 22:46 UTC, JurajNyiri commented
So it looks like when getSirenTypeList is used inside getMost it does not work on a hub, correct? Maybe we could still put it there as a separate entry instead and then identify the correct response... I will think more about it tomorrow.

2024-04-25 10:34 UTC, JurajNyiri commented
@marcosngomezi thank you for testing, I pushed a new commit in the branch https://github.com/JurajNyiri/pytapo/tree/experiment-multiple-params-getSirenTypeList .

Could you please run `tapo.getMost()` both on camera and hub and post output? No need to put it inside print as this commit is targetting a new approach which should allow us to pair request to response and therefore run the same function mutliple times.

You should see something like 

```
{'request': {'method': 'getConnectionType', 'params': {'network': {'get_connection_type': []}}}, 'response': {'result': {'link_type': 'wifi', 'ssid': 'redacted', 'rssiValue': -46, 'rssi': '4'}, 'method': 'getConnectionType'}}
{'request': {'method': 'getAlarmConfig', 'params': {'msg_alarm': {}}}, 'response': {'result': False, 'method': 'getAlarmConfig'}}
{'request': {'method': 'getAlarmPlan', 'params': {'msg_alarm_plan': {}}}, 'response': {'result': False, 'method': 'getAlarmPlan'}}
{'request': {'method': 'getSirenTypeList', 'params': {'msg_alarm': {}}}, 'response': {'result': False, 'method': 'getSirenTypeList'}}
{'request': {'method': 'getSirenTypeList', 'params': {'siren': {}}}, 'response': {'result': False, 'method': 'getSirenTypeList'}}
{'request': {'method': 'getSirenConfig', 'params': {'siren': {}}}, 'response': {'result': False, 'method': 'getSirenConfig'}}
{'request': {'method': 'getLightTypeList', 'params': {'msg_alarm': {}}}, 'response': {'result': False, 'method': 'getLightTypeList'}}
{'request': {'method': 'getSirenStatus', 'params': {'msg_alarm': {}}}, 'response': {'result': False, 'method': 'getSirenStatus'}}
{'request': {'method': 'getSirenStatus', 'params': {'siren': {}}}, 'response': {'result': False, 'method': 'getSirenStatus'}}
```

Of course with different values.

2024-04-27 17:49 UTC, JurajNyiri commented
That is interesting indeed! I do not get out of order exception. Does that happen only on hub or camera as well? That would block this approach unfortunately.

2024-04-27 17:51 UTC, marcosngomezi commented
Just pushed a possible solution  without depending on order at all [PR](https://github.com/JurajNyiri/pytapo/pull/110/files), it works for me:
 
![image](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/92400610/1f87d1bd-56f9-40e6-9e70-ae2b24cb6e8d)
```Get most Type List
Hub getConnectionType {'link_type': 'ethernet'}
Hub getAlarmConfig False
Hub getAlarmPlan False
Hub getSirenTypeList {'siren_type_list': ['Doorbell Ring 1', 'Doorbell Ring 2', 'Doorbell Ring 3', 'Doorbell Ring 4', 'Doorbell Ring 5', 'Doorbell Ring 6', 'Doorbell Ring 7', 'Doorbell Ring 8', 'Doorbell Ring 9', 'Doorbell Ring 10', 'Phone Ring', 'Alarm 1', 'Alarm 2', 'Alarm 3', 'Alarm 4', 'Dripping Tap', 'Alarm 5', 'Connection 1', 'Connection 2']}
Hub getSirenConfig {'siren_type': 'Alarm 3', 'volume': '7', 'duration': 10}
Hub getLightTypeList False
Hub getSirenStatus {'status': 'off', 'time_left': 0}
Camera getConnectionType False
Camera getAlarmConfig {'enabled': 'off', 'alarm_mode': ['siren'], 'siren_type': 'Siren', 'light_type': 'flicker', 'siren_volume': 'high', 'siren_duration': 5}
Camera getAlarmPlan {'enabled': 'off', 'alarm_plan': '0000-0000,127'}
Camera getSirenTypeList {'siren_type_list': ['Siren', 'Tone', 'Red Alert']}
Camera getSirenConfig False
Camera getLightTypeList {'light_type_list': ['flicker']}
Camera getSirenStatus {'status': 'off'}
Get Hub Siren Type List
Hub {'siren_type_list': ['Doorbell Ring 1', 'Doorbell Ring 2', 'Doorbell Ring 3', 'Doorbell Ring 4', 'Doorbell Ring 5', 'Doorbell Ring 6', 'Doorbell Ring 7', 'Doorbell Ring 8', 'Doorbell Ring 9', 'Doorbell Ring 10', 'Phone Ring', 'Alarm 1', 'Alarm 2', 'Alarm 3', 'Alarm 4', 'Dripping Tap', 'Alarm 5', 'Connection 1', 'Connection 2']}

Get Hub Siren Status
Hub {'status': 'off', 'time_left': 0} 

Get Hub Siren Config
Hub {'siren_type': 'Alarm 3', 'volume': '7', 'duration': 10} 

Get Alarm config
Hub [{'method': 'getAlarmPlan', 'error_code': -40106}, {'method': 'getAlarmConfig', 'error_code': -40106}, {'method': 'getLightTypeList', 'error_code': -40106}, {'method': 'getSirenTypeList', 'error_code': -40106}, {'method': 'getSirenStatus', 'error_code': -40106}]
Camera [{'method': 'getAlarmConfig', 'result': {'enabled': 'off', 'alarm_mode': ['siren'], 'siren_type': 'Siren', 'light_type': 'flicker', 'siren_volume': 'high', 'siren_duration': 5}, 'error_code': 0}, {'method': 'getAlarmPlan', 'result': {'enabled': 'off', 'alarm_plan': '0000-0000,127'}, 'error_code': 0}, {'method': 'getSirenTypeList', 'result': {'siren_type_list': ['Siren', 'Tone', 'Red Alert']}, 'error_code': 0}, {'method': 'getLightTypeList', 'result': {'light_type_list': ['flicker']}, 'error_code': 0}, {'method': 'getSirenStatus', 'result': {'status': 'off'}, 'error_code': 0}]
```

The problem to solve now is for the sets how to know if should be siren or msg_alarm or send both? getConnectionType is not going to be useful because both ip cameras and hub respond to it, maybe with getSirenConfig?

2024-04-27 18:03 UTC, marcosngomezi commented
Ah just realised you where trying to make a list with the multiple results, instead to just keep one, what do you think about my approach? As I said the problem is that you don't know which method was the successful and need to depend on another way to know which values should use for sets

2024-04-27 18:17 UTC, marcosngomezi commented
Looks like only the hub has the order problem, but the camera has a lot of missing result methods:
Hub request - result:
```
getDeviceInfo getDetectionConfig
getDetectionConfig getVehicleDetectionConfig
getPersonDetectionConfig getPersonDetectionConfig
getVehicleDetectionConfig getBarkDetectionConfig
getBCDConfig getMeowDetectionConfig
getPetDetectionConfig getBCDConfig
getBarkDetectionConfig getPetDetectionConfig
getMeowDetectionConfig getDeviceInfo
getGlassDetectionConfig getGlassDetectionConfig
getTamperDetectionConfig getTamperDetectionConfig
getLensMaskConfig getLensMaskConfig
getLdc getLdc
getLastAlarmInfo getLastAlarmInfo
getLedStatus getLedStatus
getTargetTrackConfig getTargetTrackConfig
getPresetConfig getPresetConfig
getFirmwareUpdateStatus getFirmwareUpdateStatus
getMediaEncrypt getMediaEncrypt
getConnectionType getConnectionType
getAlarmConfig getAlarmConfig
getAlarmPlan getAlarmPlan
getSirenTypeList getSirenTypeList
getSirenTypeList getSirenTypeList
getSirenConfig getSirenConfig
getLightTypeList getLightTypeList
getSirenStatus getSirenStatus
getSirenStatus getSirenStatus
getLightFrequencyInfo getLightFrequencyInfo
getLightFrequencyCapability getLightFrequencyCapability
getChildDeviceList getRotationStatus
getRotationStatus getNightVisionModeConfig
getNightVisionModeConfig getWhitelampStatus
getWhitelampStatus getWhitelampConfig
getWhitelampConfig getMsgPushConfig
getMsgPushConfig getSdCardStatus
getSdCardStatus getCircularRecordingConfig
getCircularRecordingConfig getRecordPlan
getRecordPlan getAudioConfig
getAudioConfig getFirmwareAutoUpgradeConfig
getFirmwareAutoUpgradeConfig getChildDeviceList
```
Camera:
```
getDeviceInfo getDeviceInfo
getDetectionConfig getDetectionConfig
getPersonDetectionConfig getPersonDetectionConfig
getVehicleDetectionConfig getVehicleDetectionConfig
getBCDConfig
getPetDetectionConfig getPetDetectionConfig
getBarkDetectionConfig
getMeowDetectionConfig
getGlassDetectionConfig
getTamperDetectionConfig
getLensMaskConfig getLensMaskConfig
getLdc getLdc
getLastAlarmInfo
getLedStatus getLedStatus
getTargetTrackConfig
getPresetConfig
getFirmwareUpdateStatus getFirmwareUpdateStatus
getMediaEncrypt getMediaEncrypt
getConnectionType
getAlarmConfig getAlarmConfig
getAlarmPlan getAlarmPlan
getSirenTypeList getSirenTypeList
getSirenTypeList
getSirenConfig
getLightTypeList getLightTypeList
getSirenStatus getSirenStatus
getSirenStatus
getLightFrequencyInfo getLightFrequencyInfo
getLightFrequencyCapability getLightFrequencyCapability
getChildDeviceList
getRotationStatus getRotationStatus
getNightVisionModeConfig getNightVisionModeConfig
getWhitelampStatus getWhitelampStatus
getWhitelampConfig getWhitelampConfig
getMsgPushConfig getMsgPushConfig
getSdCardStatus getSdCardStatus
getCircularRecordingConfig getCircularRecordingConfig
getRecordPlan getRecordPlan
getAudioConfig getAudioConfig
getFirmwareAutoUpgradeConfig
```
![image](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/92400610/412c8393-ddb6-4725-a419-11136c6401a2)

2024-04-27 18:35 UTC, JurajNyiri commented
Thats a great idea, I would say instead of throwing the exception, we could convert it to a list instead. That way HA can then go into the list and find the correct property it is looking for.

2024-04-27 18:38 UTC, JurajNyiri commented
I am going to accept PR and do the changes above, then I will push the code for you to test again.

2024-04-27 18:46 UTC, marcosngomezi commented
not sure about the list  because there is not going to be a way to know which one is first and second anyway, because can be in different order, and it would force tapo-control to always check if it is a dictionary or a list, are you sure that is worth making it a list? for what we have seen there are no devices that respond to both, if some day appears, there should be some extra research to understand why it responds to both, its an strange case to have two sirens on the same device

2024-04-27 18:46 UTC, JurajNyiri commented
I have pushed a new commit making everything a list to keep it consistent and removed the exception. 

https://github.com/JurajNyiri/pytapo/commit/a5f2213a7cd8bede335a0bff53ae792b937764db

Could you please test?

As for tapo integration I can refactor it so that it can accept these values as a list and look for the property it needs in the loop and as soon as it finds it break the loop.

2024-04-27 18:47 UTC, JurajNyiri commented
Actually give me a second, I will try to make it more robust so that the number of requests always equals the number of responses, even if response fails...

2024-04-27 18:54 UTC, marcosngomezi commented
I left a pair of comments on the [commit ](https://github.com/JurajNyiri/pytapo/commit/a5f2213a7cd8bede335a0bff53ae792b937764db)

2024-04-27 19:05 UTC, JurajNyiri commented
@marcosngomezi pushed another [commit](https://github.com/JurajNyiri/pytapo/commit/5416d5c63cae8fbe0cd6ed348e0b300815315b7e). Let me know if it works please.

```
getConnectionType
[{'link_type': 'wifi', 'ssid': 'redacted', 'rssiValue': -44, 'rssi': '4'}]
getAlarmConfig
[False]
getAlarmPlan
[False]
getSirenTypeList
[False, False]
getSirenConfig
[False]
getLightTypeList
[False]
getSirenStatus
[False, False]
```

2024-04-27 19:19 UTC, JurajNyiri commented
As for this PR with the new codebase (assuming it will work).

What I think we can afford to do is inside `getCamData(hass, controller):` just change everything starting with ` data[` to ` data[...function...][0]` except for `getSirenTypeList` and `getSirenStatus`. As we control pytapo code / version there is no need for universal loop or length checking on the rest.

As for the 2 that are there twice, both of these are not in there yet in the main branch, so for these what we can do is create a for loop and find the first expected value for them and save accordingly.

2024-04-27 19:30 UTC, marcosngomezi commented
Its working:
```
Get most Type List
Hub getConnectionType [{'link_type': 'ethernet'}]
Hub getAlarmConfig [False]
Hub getAlarmPlan [False]
Hub getSirenTypeList [{'siren_type_list': ['Doorbell Ring 1', 'Doorbell Ring 2', 'Doorbell Ring 3', 'Doorbell Ring 4', 'Doorbell Ring 5', 'Doorbell Ring 6', 'Doorbell Ring 7', 'Doorbell Ring 8', 'Doorbell Ring 9', 'Doorbell Ring 10', 'Phone Ring', 'Alarm 1', 'Alarm 2', 'Alarm 3', 'Alarm 4', 'Dripping Tap', 'Alarm 5', 'Connection 1', 'Connection 2']}, False]
Hub getSirenConfig [{'siren_type': 'Alarm 3', 'volume': '7', 'duration': 10}]
Hub getLightTypeList [False]
Hub getSirenStatus [{'status': 'off', 'time_left': 0}, False]
Camera getConnectionType [False]
Camera getAlarmConfig [{'enabled': 'off', 'alarm_mode': ['siren'], 'siren_type': 'Siren', 'light_type': 'flicker', 'siren_volume': 'high', 'siren_duration': 5}]
Camera getAlarmPlan [{'enabled': 'off', 'alarm_plan': '0000-0000,127'}]
Camera getSirenTypeList [{'siren_type_list': ['Siren', 'Tone', 'Red Alert']}, False]
Camera getSirenConfig [False]
Camera getLightTypeList [{'light_type_list': ['flicker']}]
Camera getSirenStatus [{'status': 'off'}, False]
```

2024-04-27 19:34 UTC, marcosngomezi commented
Would you use same siren and config components for both types of sirens or keep it as siren and hub siren components in the integration? makes sense to have just one now I suppose

2024-04-27 19:35 UTC, JurajNyiri commented
I think we can use the same, as the response is the same from the point of HA there is no difference, both have key "siren_type_list"

2024-04-27 19:36 UTC, JurajNyiri commented
@marcosngomezi I have just pushed new version to pytapo https://pypi.org/manage/project/pytapo/release/3.3.20/

2024-04-27 19:38 UTC, JurajNyiri commented
Let me know if you are OK with updating the rest like described above for breaking changes, if not I can do the changes on main. We should also now use the types reported by camera instead of hardcoding them inside the code.

2024-04-27 19:38 UTC, JurajNyiri commented
Please make sure to test also if the integration uses the cached values, so that we do not re-request data that have been already retrieved via getMost. You should see a lot of "Found cached capability {check_function}, creating {cls.__name__}"

2024-04-27 19:39 UTC, marcosngomezi commented
sure I can do the changes

2024-04-27 19:45 UTC, JurajNyiri commented
Headsup, you will need to also modify this function since everything is now a list. 

<img width="691" alt="Screenshot 2024-04-27 at 21 44 22" src="https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/5785999/3bf080f3-b94e-481a-ba9e-940865fcb0db">

For example, in `and "switch" in rawData["getLdc"]["image"]` you would need `rawData["getLdc"][0]["image"]` I think.

2024-05-01 15:03 UTC, marcosngomezi commented on custom_components/tapo_control/number.py
> +#TODO on hub siren is from 1 to 10 but on cameras is low normal high, maybe we could handle it as number and convert it to enum just for cameras, being [1-3] low, [4-6] normal and [7-10] high?
what do you think?

2024-05-01 15:06 UTC, JurajNyiri commented on custom_components/tapo_control/number.py
> +#TODO on hub siren is from 1 to 10 but on cameras is low normal high, maybe we could handle it as number and convert it to enum just for cameras, being [1-3] low, [4-6] normal and [7-10] high?
I like that! I would say low can be 2 normal 5 and 10 high? Please test it out to see what feels the best

2024-05-01 15:06 UTC, marcosngomezi commented on custom_components/tapo_control/number.py
> +#TODO max value for c420 is 300 while on hub is 599, to validate on other cameras
could you validate the max value on your camera/s?
method: `"setAlarmConfig" `
params: `{"msg_alarm": { "siren_duration": 5 }}`

2024-05-01 15:08 UTC, JurajNyiri commented on custom_components/tapo_control/number.py
> +#TODO on hub siren is from 1 to 10 but on cameras is low normal high, maybe we could handle it as number and convert it to enum just for cameras, being [1-3] low, [4-6] normal and [7-10] high?
Or actually the other way around like you suggested. Keep it 1-10 but convert to values for hub.

2024-05-01 15:08 UTC, marcosngomezi commented on custom_components/tapo_control/select.py
> +# TODO c420 alarm_mode has alarm_mode siren, check compatibility of method
I saw that siren was considered on pytapo but not here, probably not working correctly, to check

2024-05-01 15:08 UTC, JurajNyiri commented on custom_components/tapo_control/number.py
> +#TODO max value for c420 is 300 while on hub is 599, to validate on other cameras
What happens if we set 599 on camera?

2024-05-01 15:09 UTC, marcosngomezi commented on custom_components/tapo_control/siren.py
> +    # currently the shortest between configured siren duration and this service call duration is the one that will have impact, also ensuring the duration with siren config would allow to aboid the a
What do you think about this two points?

2024-05-01 15:11 UTC, marcosngomezi commented on custom_components/tapo_control/number.py
> +#TODO on hub siren is from 1 to 10 but on cameras is low normal high, maybe we could handle it as number and convert it to enum just for cameras, being [1-3] low, [4-6] normal and [7-10] high?
also could be from 1 to 3 just for camera volume Im thinking

2024-05-01 15:11 UTC, marcosngomezi commented on custom_components/tapo_control/number.py
> +#TODO max value for c420 is 300 while on hub is 599, to validate on other cameras
throws error

2024-05-01 15:13 UTC, marcosngomezi commented
Hi there @JurajNyiri not yet finished, numbers are remaining and some TODOs, but some questions and need of validation on other cameras rised.

2024-05-01 15:17 UTC, marcosngomezi commented on custom_components/tapo_control/number.py
> +#TODO on hub siren is from 1 to 10 but on cameras is low normal high, maybe we could handle it as number and convert it to enum just for cameras, being [1-3] low, [4-6] normal and [7-10] high?
if convert from enum to numbers we limit functionality on the hub, that with the other options does not

2024-05-01 23:28 UTC, JurajNyiri commented on custom_components/tapo_control/number.py
> +#TODO on hub siren is from 1 to 10 but on cameras is low normal high, maybe we could handle it as number and convert it to enum just for cameras, being [1-3] low, [4-6] normal and [7-10] high?
Agree, lets go with numbers and convert it to enum for hub. Thank you!

2024-05-04 23:12 UTC, JurajNyiri commented on custom_components/tapo_control/number.py
> +#TODO max value for c420 is 300 while on hub is 599, to validate on other cameras
I am a bit confused, there is no siren_duration anywhere in the code of pytapo. 

I ran it anyways:

```
print(tapo.executeFunction("setAlarmConfig", {"msg_alarm": {"siren_duration": 5}}))

Traceback (most recent call last):
  File "/Users/jnyiri/repos/pytapo/test2.py", line 21, in <module>
    print(tapo.executeFunction("setAlarmConfig", {"msg_alarm": {"siren_duration": 5}}))
  File "/Users/jnyiri/repos/pytapo/pytapo/__init__.py", line 510, in executeFunction
    raise Exception(
Exception: Error: Function not supported, Response: {"method": "setAlarmConfig", "result": {}, "error_code": -40210}
```

2024-05-04 23:19 UTC, JurajNyiri commented on custom_components/tapo_control/number.py
> +#TODO max value for c420 is 300 while on hub is 599, to validate on other cameras
As for the value, we could set this to `self._attr_native_max_value = 300` if hass.data[DOMAIN][entry.entry_id]["isParent"] is False.

2024-05-04 23:21 UTC, JurajNyiri commented on custom_components/tapo_control/select.py
> +# TODO c420 alarm_mode has alarm_mode siren, check compatibility of method
Could you elaborate? I am not sure what you mean. How can I help?

2024-05-04 23:24 UTC, JurajNyiri commented on custom_components/tapo_control/siren.py
> +    # currently the shortest between configured siren duration and this service call duration is the one that will have impact, also ensuring the duration with siren config would allow to aboid the a
Previously on cameras on older firmwares there was no way how to stop the alarm after executing it after some time on camera (and I think there still isnt?), therefore this sleep was needed. Does this method work correctly on hub? If so, we should keep it in order to ensure reverse compatibility.

2024-05-04 23:24 UTC, JurajNyiri commented
Hey @marcosngomezi thank you for all your updates. Let me know if I can help in any way with this PR.

2024-05-04 23:28 UTC, JurajNyiri commented on custom_components/tapo_control/siren.py
> +            )
We should move this to pytapo so that the lib does not call performRequest directly anywhere.

2024-05-04 23:32 UTC, JurajNyiri commented on custom_components/tapo_control/utils.py
> +        alarmData = data["getAlarmConfig"][0]
getAlarm:

```
{'enabled': 'off', 'light_alarm_enabled': 'on', 'alarm_mode': ['sound', 'light'], 'alarm_type': '0', 'light_type': '1', 'sound_alarm_enabled': 'on', 'alarm_volume': 'high', 'alarm_duration': '0'}
```

getAlarmConfig:

```
[{'method': 'getAlarmConfig', 'result': {}, 'error_code': -40210}, {'method': 'getAlarmPlan', 'result': {}, 'error_code': -40210}, {'method': 'getSirenTypeList', 'result': {}, 'error_code': -40210}, {'method': 'getLightTypeList', 'result': {}, 'error_code': -40210}, {'method': 'getSirenStatus', 'result': {}, 'error_code': -40210}]
```

This change will break cameras.

2024-05-04 23:36 UTC, JurajNyiri requested changes

2024-05-04 23:36 UTC, JurajNyiri commented on custom_components/tapo_control/utils.py
> +            alarm = data["getSirenStatus"][0]["status"]
This change will break cameras, see above.

It will need to be handled separately.

2024-05-09 22:11 UTC, JurajNyiri commented
Hi @marcosngomezi I had to push a new update to fix unrelated issue, please rebase this if you get the chance and see my comments above.

2024-05-18 23:00 UTC, marcosngomezi commented on custom_components/tapo_control/number.py
> +#TODO max value for c420 is 300 while on hub is 599, to validate on other cameras
On the getAlarmConfig I get the next response from cameras:
` [{'enabled': 'off', 'alarm_mode': ['siren'], 'siren_type': 'Siren', 'light_type': 'flicker', 'siren_volume': 'normal', 'siren_duration': 300}]`
And I can change any value with the setAlarmConfig, you dont have siren_duration in your cameras?

2024-05-19 00:52 UTC, marcosngomezi commented on custom_components/tapo_control/utils.py
> +        alarmData = data["getAlarmConfig"][0]
Ok then we could get the getLastAlarmInfo one as third option if previous ones didnt work, because is the least accurate but for compatibility with those cases, currently is the first option to be considered

2024-05-19 01:05 UTC, marcosngomezi commented on custom_components/tapo_control/number.py
> +#TODO max value for c420 is 300 while on hub is 599, to validate on other cameras
from another comment I see that is probably alarm_duration in some cameras, in that case could you test max value for `print(tapo.executeFunction("setAlarmConfig", {"msg_alarm": {"alarm_duration": 5}}))`

2024-05-19 01:16 UTC, marcosngomezi commented on custom_components/tapo_control/select.py
> +# TODO c420 alarm_mode has alarm_mode siren, check compatibility of method
at the C420 is used the string `siren `in place of `sound`, in this select updateTapo method is not being considered the "siren" value, I will check on my camera and came back

2024-06-01 23:33 UTC, marcosngomezi commented on custom_components/tapo_control/utils.py
> +            alarm = data["getSirenStatus"][0]["status"]
done

2024-06-01 23:33 UTC, marcosngomezi commented on custom_components/tapo_control/utils.py
> +        alarmData = data["getAlarmConfig"][0]
done

2024-06-02 00:05 UTC, marcosngomezi commented on custom_components/tapo_control/number.py
> +#TODO on hub siren is from 1 to 10 but on cameras is low normal high, maybe we could handle it as number and convert it to enum just for cameras, being [1-3] low, [4-6] normal and [7-10] high?
done

2024-06-02 00:06 UTC, marcosngomezi commented on custom_components/tapo_control/number.py
> +#TODO max value for c420 is 300 while on hub is 599, to validate on other cameras
done

2024-06-02 00:12 UTC, marcosngomezi commented on custom_components/tapo_control/siren.py
> +    # currently the shortest between configured siren duration and this service call duration is the one that will have impact, also ensuring the duration with siren config would allow to aboid the a
some cameras have alarm_duration and siren_duration, we could use it on those, 
what I see now about this comment is that it would change the config previously setted, I think that is better to leave it as it is and if the user wants to use another config can change it as a previous step to calling the service

2024-06-22 00:58 UTC, marcosngomezi commented
Hi there @JurajNyiri , sorry for the delay, trying to finish this PR, I think is ready for a review, also have tested it and is working as expected.
There are two "issues" that I think are not related but maybe you know better:

- `Config entry * has already been setup!` Sound like for some reason is running twice the creation? or is it normal when restarting  HA?
![image](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/92400610/39f5a9f5-fbca-4f8a-9e54-ce2eeb3d4a53)
- Select and switch and select reports to be taking over 10 seconds, not sure if normal or there is something to improve.
![image](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/92400610/d219815c-2bf6-4b8c-953b-dde069f615c1)

2024-06-25 18:36 UTC, JurajNyiri commented
Thank you!

> Config entry * has already been setup!

I saw some users with this issue but have never been able to track it down or replicate it. Usually I told users to remove all entries in jsons for tapo_control and that solved it. Might be some misconfiguration, somehow, via some edge case...

> Select and switch and select reports to be taking over 10 seconds

Some cameras are slower, some of mine take a rather long time to respond, not much we can do.

2024-06-25 18:37 UTC, JurajNyiri commented on custom_components/tapo_control/siren.py
> +                )
I will focus on testing this, ideally we should move it to pytapo function so that we do not need executeFunction call directly.

2024-06-25 18:38 UTC, JurajNyiri commented on custom_components/tapo_control/utils.py
> +    return [pytapoFunctionName]
Smart!

2024-06-25 18:39 UTC, JurajNyiri commented on custom_components/tapo_control/utils.py
> +    return [pytapoFunctionName]
Thinking about this more though, how does it handle a case where a function is passed which does not match? Since now it will never return an empty list which I think is incorrect.

2024-06-27 22:14 UTC, marcosngomezi commented on custom_components/tapo_control/utils.py
> +    return [pytapoFunctionName]
if it does not exists the if of line off line 1389` if function in rawData and rawData[function][0]` is going to fail and return false that is the correct answer I think

2024-06-27 22:18 UTC, marcosngomezi commented on custom_components/tapo_control/utils.py
> +    return [pytapoFunctionName]
I see the method as a mapper for exceptions, doesnt make sense to me to have mappings from to the same value, and determining if is a valid function should be based on camData data not on this method in my opinion

2024-06-28 15:50 UTC, JurajNyiri requested changes
Thank you for your updates! 

Comments below in review addressed in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/commit/aae7b3557e372e93263aac8959011913c685e5b2

Please merge, clean up and let me know if it works, if all works as expected I will do final testing with C200 for all the features.

2024-06-28 15:50 UTC, JurajNyiri commented on custom_components/tapo_control/utils.py
> +            alarmData = data["getLastAlarmInfo"]["msg_alarm"]["chn1_msg_alarm_info"]
Missing [0]

2024-06-28 15:50 UTC, JurajNyiri commented on custom_components/tapo_control/utils.py
> +            alarmData = data["getLastAlarmInfo"]["msg_alarm"]["chn1_msg_alarm_info"]
2024-06-28 15:13:14.298 ERROR (MainThread) [custom_components.tapo_control] getLastAlarmInfo unexpected error err=TypeError('list indices must be integers or slices, not str'), type(err)=<class 'TypeError'>

2024-06-28 15:50 UTC, JurajNyiri commented on custom_components/tapo_control/utils.py
> +        alarmStatus = data["getSirenStatus"][0]["status"]
This can be (and is on my camera) [False, False].

This results in 

```
2024-06-28 15:20:31.453 ERROR (MainThread) [custom_components.tapo_control] getSirenStatus unexpected error err=TypeError("'bool' object is not subscriptable"), type(err)=<class 'TypeError'>
```

2024-06-28 15:50 UTC, JurajNyiri commented on custom_components/tapo_control/utils.py
> +        alarmStatus = data["getSirenStatus"][0]["status"]
```
if (
            data["getSirenStatus"][0] is not False
            and "status" in data["getSirenStatus"][0]
        ):
            alarmStatus = data["getSirenStatus"][0]["status"]
```

2024-06-28 15:50 UTC, JurajNyiri commented on custom_components/tapo_control/utils.py
> +            alarmData = data["getLastAlarmInfo"]["msg_alarm"]["chn1_msg_alarm_info"]
```
alarmData = data["getLastAlarmInfo"][0]["msg_alarm"]["chn1_msg_alarm_info"]
```

2024-06-28 15:50 UTC, JurajNyiri commented on custom_components/tapo_control/utils.py
> +    if alarmConfig != None:
is not None

2024-06-28 15:50 UTC, JurajNyiri commented on custom_components/tapo_control/utils.py
> +        except Exception:
```Unable to connect to Tapo: Cameras Control controller: cannot access local variable 'err' where it is not associated with a value```

2024-06-28 15:50 UTC, JurajNyiri commented on custom_components/tapo_control/utils.py
> +        except Exception:
`except Exception as err:`

2024-06-28 15:50 UTC, JurajNyiri commented on custom_components/tapo_control/utils.py
> +        except Exception:
After fixing the err var

```
2024-06-28 15:26:49.357 ERROR (MainThread) [custom_components.tapo_control] getSirenTypeList unexpected error err=TypeError("'bool' object is not subscriptable"), type(err)=<class 'TypeError'>
```

2024-06-28 15:50 UTC, JurajNyiri commented on custom_components/tapo_control/utils.py
> +        except Exception:
```
if (
                data["getSirenTypeList"][0] is not False
                and "siren_type_list" in data["getSirenTypeList"][0]
            ):
```

2024-06-28 15:50 UTC, JurajNyiri commented on custom_components/tapo_control/siren.py
>          )
<img width="327" alt="Screenshot 2024-06-28 at 17 28 18" src="https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/assets/5785999/70d8c557-bcaa-42ca-8ae1-28e7c6c01f47">

Siren became unavailable after fixes described in review and this PR on my camera

2024-06-28 15:50 UTC, JurajNyiri commented on custom_components/tapo_control/siren.py
> -        )
After changing it back to getAlarm and triggering, it no longer sounds without this.

2024-06-28 15:50 UTC, JurajNyiri commented on custom_components/tapo_control/siren.py
> -        )
Stop also no longer works with my camera with these changes

2024-06-28 15:50 UTC, JurajNyiri commented on custom_components/tapo_control/siren.py
> +    async def async_turn_off(self, send: bool | None = None, **kwargs) -> None:
For me, the send is always None, so this never executes. Why was it added?

2024-06-29 14:33 UTC, marcosngomezi commented on custom_components/tapo_control/siren.py
> +    async def async_turn_off(self, send: bool | None = None, **kwargs) -> None:
Its added because my cameras return the time_left param on the response(line126 and 84)and there is no need to send the stop command to the camera, is just for updating the HA status, maybe there is a better way to do, I only saw it being called on the` _turn_off_after` method but now I get that it is part of the entity interface, if send is None it enters to the else right?, there should be no error

2024-06-29 14:36 UTC, marcosngomezi commented on custom_components/tapo_control/siren.py
>          )
I understanded that `getSirenTypeList `was the common factor between cameras with siren, `getAlarm `is no available on C420s, we have to do some kind of OR for both methods then

2024-06-29 14:42 UTC, marcosngomezi commented on custom_components/tapo_control/siren.py
> -        )
weird, the first command in the multipleRequest, is the same that is being sended in the startManualAlarm method https://github.com/JurajNyiri/pytapo/blob/bd5c6d579d618d1e47a9049873b7e57c9d74ffb0/pytapo/__init__.py#L1628
Could you confirm that 
```
performRequest(
            {
                "method": "do",
                "msg_alarm": {"manual_msg_alarm": {"action": "start"}},
            })
```
works, but 
```
performRequest,(
                {
                    "method": "multipleRequest",
                    "params": {
                        "requests": [
                            {
                                "method": "do",
                                "params": {
                                    "msg_alarm": {
                                        "manual_msg_alarm": {"action": "start"}
                                    }
                                },
                            },
                        ]
                    },
                })
```
dont?

2024-06-29 14:43 UTC, marcosngomezi commented on custom_components/tapo_control/siren.py
> -        )
same thing to check than with the start

2024-06-29 14:47 UTC, marcosngomezi commented on custom_components/tapo_control/utils.py
> +    if alarmConfig != None:
I dont understand the comment, if we got alarmConfig from some of the previous sources, we search for typelist, but if none of them worked makes no sense to search it

2024-06-29 14:49 UTC, marcosngomezi commented on custom_components/tapo_control/utils.py
> +        alarmStatus = data["getSirenStatus"][0]["status"]
it should be initialized as false then

2024-06-29 16:01 UTC, JurajNyiri commented on custom_components/tapo_control/utils.py
> +    if alarmConfig != None:
Check my commit, it's linter complaining, just a better practice, instead of `!=` do `if alarmConfig is not None:`

2024-06-29 16:03 UTC, JurajNyiri commented on custom_components/tapo_control/siren.py
>          )
I see, we might need a custom logic then... or possibly just call it twice, once for getAlarm and once for getSirenTypeList. It might create 2 entities for some cameras though we do not know of, so maybe if getAlarm failed to create, do getSirenTypeList

2024-06-29 16:08 UTC, JurajNyiri commented on custom_components/tapo_control/siren.py
> -        )
Correct, the one via multipleRequest does not work. This call was found long time ago from other chinese cameras - not Tapo cameras, so it might be something they copied in but did not officially support and it was never supported via the app in the beginning when it was found. Might explain the inconsistencies we are facing here.

2024-06-29 16:09 UTC, JurajNyiri commented on custom_components/tapo_control/siren.py
> -        )
Same.

```

tapo.performRequest(
    {
        "method": "do",
        "msg_alarm": {"manual_msg_alarm": {"action": "stop"}},
    }
)
```
works.

```
tapo.performRequest(
    {
        "method": "multipleRequest",
        "params": {
            "requests": [
                {
                    "method": "do",
                    "msg_alarm": {"manual_msg_alarm": {"action": "stop"}},
                },
            ]
        },
    }
)
```
doesn't.

2024-06-29 16:11 UTC, JurajNyiri commented on custom_components/tapo_control/siren.py
> +    async def async_turn_off(self, send: bool | None = None, **kwargs) -> None:
When user manually switches off the siren via the siren switch it always goes to else (at least for my camera) which does not execute any command on the camera therefore the siren is not stopped.

2024-06-29 16:12 UTC, JurajNyiri commented
@marcosngomezi if you haven't yet, check my [commit](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/commit/aae7b3557e372e93263aac8959011913c685e5b2) and that branch, just in case you missed my main comment on the review, might save you some time as I addressed most of the above, we just now need to make it work on both cameras as we discussed in the comments now.

2024-06-29 16:15 UTC, JurajNyiri commented on custom_components/tapo_control/utils.py
> +        alarmStatus = data["getSirenStatus"][0]["status"]
The issue is that `data["getSirenStatus"][0]` itself is False, so when we try to read status off of it it fails as boolean does not have dict entries

2024-06-29 16:36 UTC, marcosngomezi commented
Yes I saw it, lets resolve the pending comments and I will do the merge, remaining fixs and testing

2024-06-29 16:38 UTC, marcosngomezi commented on custom_components/tapo_control/utils.py
> +        alarmStatus = data["getSirenStatus"][0]["status"]
yes, I mean in the cases that is missing, i will default the status to false, as we wouldnt know, but probably is false

2024-07-01 04:36 UTC, marcosngomezi commented on custom_components/tapo_control/siren.py
> +    async def async_turn_off(self, send: bool | None = None, **kwargs) -> None:
right, sorry I was confusing elses with the is_hub, we should change then to `send == None or send` right?

2024-07-01 06:37 UTC, JurajNyiri commented on custom_components/tapo_control/siren.py
> +    async def async_turn_off(self, send: bool | None = None, **kwargs) -> None:
I think we should just remove it completely, both arg and condition, I do not see how it could be anything other than None but maybe I am missing something.

2024-07-11 00:40 UTC, marcosngomezi commented on custom_components/tapo_control/siren.py
> +    async def async_turn_off(self, send: bool | None = None, **kwargs) -> None:
its being called with send False in the method  _turn_off_after, in line 84 when it is called from line 128 ( from this same file)

2024-07-11 09:49 UTC, JurajNyiri commented on custom_components/tapo_control/siren.py
> +    async def async_turn_off(self, send: bool | None = None, **kwargs) -> None:
The issue is that it does not get executed when the user manually turns off the switch. The issue is some cameras do not have "time_left" reporting and even if they have - user has to be able to manually turn off the siren.

2024-07-20 15:37 UTC, marcosngomezi commented on custom_components/tapo_control/siren.py
> +    async def async_turn_off(self, send: bool | None = None, **kwargs) -> None:
yes I got it, changing to `send: bool | None = True`, should fixit right?

2024-07-20 15:56 UTC, marcosngomezi commented on custom_components/tapo_control/utils.py
> +            alarmData = data["getLastAlarmInfo"]["msg_alarm"]["chn1_msg_alarm_info"]
done

2024-07-20 15:58 UTC, marcosngomezi commented on custom_components/tapo_control/utils.py
> +    if alarmConfig != None:
done

2024-07-20 15:58 UTC, marcosngomezi commented on custom_components/tapo_control/utils.py
> +        except Exception:
done

2024-07-20 15:58 UTC, marcosngomezi commented on custom_components/tapo_control/siren.py
>          )
done

2024-07-20 15:58 UTC, marcosngomezi commented on custom_components/tapo_control/siren.py
> -        )
done

2024-07-20 15:58 UTC, marcosngomezi commented on custom_components/tapo_control/siren.py
> -        )
done

2024-07-20 15:59 UTC, marcosngomezi commented on custom_components/tapo_control/siren.py
> +    async def async_turn_off(self, send: bool | None = None, **kwargs) -> None:
done

2024-07-20 15:59 UTC, marcosngomezi commented on custom_components/tapo_control/utils.py
> +        alarmStatus = data["getSirenStatus"][0]["status"]
done

2024-07-20 16:25 UTC, marcosngomezi commented
Did a mess with commits history, sorry, but is ready for another review, everything working on my side.

2024-07-20 21:44 UTC, JurajNyiri commented
❗ [this](https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/pull/559/files#diff-4c3da84fa2e10c36baee514eccf5c769e557e7723a1f48fc9258c3b344f88e7bR1443 .) might not work with https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/pull/632 .

2024-07-20 21:46 UTC, JurajNyiri commented
Given the changes in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/pull/632 I think we should remove the changes to the mapper, or think of another way to do that.

2024-07-20 22:27 UTC, JurajNyiri commented
Looking into this now, siren still does not work properly on my C200 v3, will post details soon...

2024-07-20 22:32 UTC, JurajNyiri commented
I will change base branch and finish this just to get this done since it's hard for you to test

2024-07-20 22:33 UTC, JurajNyiri approved these changes
Thank you! Going to fix the small leftover things in follow up commits

2024-07-20 22:33 UTC, merged

2024-07-20 23:11 UTC, JurajNyiri commented
Released in https://github.com/JurajNyiri/HomeAssistant-Tapo-Control/releases/tag/5.4.31 !

2024-07-20 23:20 UTC, marcosngomezi commented
Nice!, I dont see the issue with #632, but we can review it on that PR

2024-07-20 23:27 UTC, JurajNyiri commented
Siren duration and siren volume has been added to my 

C520WS
by TP-Link
Firmware: 1.2.6 Build 231130 Rel.72992n 

But when running it it says the function is not supported, we will need to fix that.