Use _attr_native_value instead of _attr_state in sensor entity
JurajNyiri/HomeAssistant-Tapo-Control pull request #626
Opened 2024-07-16 22:03 UTC by natekspencer

The `state` property of a sensor entity is marked as final in Home Assistant code and should not be used for a sensor's state. Instead the recommendation is to use the `native_value` property. This switches the code to use `_attr_native_value` instead of `_attr_state` as well as some additional cleanup in the sensor.py file for readability.

See https://github.com/home-assistant/core/blob/dev/homeassistant/components/sensor/__init__.py#L538
and https://developers.home-assistant.io/docs/core/entity/sensor

2024-07-20 10:48 UTC, JurajNyiri requested changes
Thank you for the PR! Left some minor comments, once addressed I will test and merge

2024-07-20 10:48 UTC, JurajNyiri commented on custom_components/tapo_control/sensor.py
> +            cam_data: dict = entry["camData"]
Please rename to camData to be consistent with other entities

2024-07-20 10:48 UTC, JurajNyiri commented on custom_components/tapo_control/sensor.py
> +    sensors = await setup_entities(entry)
Please rename back to setupEntities to be consistent

2024-07-20 10:48 UTC, JurajNyiri commented on custom_components/tapo_control/sensor.py
> +    for child_device in entry["childDevices"]:
Please rename back to be consistent

2024-07-20 10:48 UTC, JurajNyiri commented on custom_components/tapo_control/sensor.py
> +        """Update the entity."""
Remove comment

2024-07-20 15:34 UTC, natekspencer commented on custom_components/tapo_control/sensor.py
> +            cam_data: dict = entry["camData"]
Will do! I was trying to follow python naming standards (and resolve pylint complaining in my IDE) and planned on making this change to all other entities, but wanted to start off with just one. But if you'd rather keep it this way instead I'll revert!

2024-08-06 18:07 UTC, JurajNyiri commented
Thank you for the reminder and PR, I was very busy lately. I will try to review and test this during the weekend.

2024-08-06 18:08 UTC, natekspencer commented
> Thank you for the reminder and PR, I was very busy lately. I will try to review and test this during the weekend.

No worries, just didn't want it to get lost!

2024-08-12 21:21 UTC, merged

2024-08-12 21:29 UTC, JurajNyiri commented
Thank you! Merged